//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernMetroUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class HosDeparts
    {
        public short DepartId { get; set; }
        public string DepartNameA { get; set; }
        public string DepartNameE { get; set; }
        public byte DepartNo { get; set; }
        public Nullable<byte> DepartLocationTypeId { get; set; }
        public string Addrees { get; set; }
        public string Phones { get; set; }
        public string Discription { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string Notes { get; set; }
    }
}
